/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 6.2.2 EDK_Gm.13.6
* DO NOT EDIT.
*
* Copyright (c) 2003 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x80002100
#define STDOUT_BASEADDRESS 0x80002100

/******************************************************************/

#define XPAR_DLMB_CNTLR_BASEADDR 0x00000000
#define XPAR_DLMB_CNTLR_HIGHADDR 0x00001FFF
#define XPAR_ILMB_CNTLR_BASEADDR 0x00000000
#define XPAR_ILMB_CNTLR_HIGHADDR 0x00001FFF

/******************************************************************/

#define XPAR_XUARTLITE_NUM_INSTANCES 2
#define XPAR_DEBUG_MODULE_BASEADDR 0x80002000
#define XPAR_DEBUG_MODULE_HIGHADDR 0x800020FF
#define XPAR_DEBUG_MODULE_DEVICE_ID 0
#define XPAR_DEBUG_MODULE_BAUDRATE 0
#define XPAR_DEBUG_MODULE_USE_PARITY 0
#define XPAR_DEBUG_MODULE_ODD_PARITY 0
#define XPAR_DEBUG_MODULE_DATA_BITS 0
#define XPAR_RS232_BASEADDR 0x80002100
#define XPAR_RS232_HIGHADDR 0x800021FF
#define XPAR_RS232_DEVICE_ID 1
#define XPAR_RS232_BAUDRATE 9600
#define XPAR_RS232_USE_PARITY 0
#define XPAR_RS232_ODD_PARITY 0
#define XPAR_RS232_DATA_BITS 8

/******************************************************************/

#define XPAR_XGPIO_NUM_INSTANCES 3
#define XPAR_LEDS_8BIT_BASEADDR 0x80002200
#define XPAR_LEDS_8BIT_HIGHADDR 0x800023FF
#define XPAR_LEDS_8BIT_DEVICE_ID 0
#define XPAR_LEDS_8BIT_INTERRUPT_PRESENT 0
#define XPAR_LEDS_8BIT_IS_DUAL 0
#define XPAR_PUSH_BUTTONS_3BIT_BASEADDR 0x80002400
#define XPAR_PUSH_BUTTONS_3BIT_HIGHADDR 0x800025FF
#define XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID 1
#define XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT 0
#define XPAR_PUSH_BUTTONS_3BIT_IS_DUAL 0
#define XPAR_DIP_SWITCHES_8BIT_BASEADDR 0x80002800
#define XPAR_DIP_SWITCHES_8BIT_HIGHADDR 0x800029FF
#define XPAR_DIP_SWITCHES_8BIT_DEVICE_ID 2
#define XPAR_DIP_SWITCHES_8BIT_INTERRUPT_PRESENT 0
#define XPAR_DIP_SWITCHES_8BIT_IS_DUAL 0

/******************************************************************/

#define XPAR_XTMRCTR_NUM_INSTANCES 1
#define XPAR_DELAY_BASEADDR 0x80002600
#define XPAR_DELAY_HIGHADDR 0x800026FF
#define XPAR_DELAY_DEVICE_ID 0

/******************************************************************/

#define XPAR_OPB_7SEGLED_0_BASEADDR 0x80002A00
#define XPAR_OPB_7SEGLED_0_HIGHADDR 0x80002AFF

/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 1
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
#define XPAR_XINTC_NUM_INSTANCES 1
#define XPAR_OPB_INTC_0_BASEADDR 0x80002C00
#define XPAR_OPB_INTC_0_HIGHADDR 0x80002DFF
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000

/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x80002C00
#define XPAR_INTC_SINGLE_HIGHADDR 0x80002DFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_DELAY_INTERRUPT_MASK 0X000001
#define XPAR_OPB_INTC_0_DELAY_INTERRUPT_INTR 0

/******************************************************************/


